apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-ghost-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blog-ghost
    spec:
      containers:
      - name: ghost
        image: ghost:1-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: ghostport
          containerPort: 2368
        env:
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: 172.17.0.14
        - name: database__connection__user
          value: root
        - name: database__connection__password
          value: welcome
        - name: database__connection__database
          value: ghost
        - name: database__connection__port
          value: "3306"